controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


content_list:
    path: '/contenu/liste'
    controller: 'App\Controller\ContentController::list'

content_show:
    path: '/contenu/{id}'
    controller: 'App\Controller\ContentController::show'

